# Site settings
title: Jacqueline Currie
header-img: http://thecuriosityhub.com/img/wedobanner.jpg
email: jacqueline@thecuriosityhub.com
copyright_name: Curiosity Hub LLC
description: "Inspiring the next generatin of engineerings"
baseurl: ""
url: "http://thecuriosityhub.com"
twitter_username: jncurrie
github_username:  jncurrie
facebook_username:  thecuriosityhub
email_username:  jacqueline@thecuriosityhub.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
google_tracking_id: UA-47047791-1

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
